# -*- coding: utf-8 -*-
"""BusquedaYSistemasBasadosEnReglas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j2MaCGEzDxM3LgjqmLlUKb_g0WlKfnmJ
"""



"""
Sistema Inteligente Basado en Conocimiento para el Sistema de Transporte TransMilenio
Modelado con representación del conocimiento y motor de reglas lógicas de inferencia.
"""

from typing import List, Dict, Optional, Tuple

# ==========================================================
# 1. BASE DE CONOCIMIENTO (Hechos del Dominio)
# ==========================================================

# Estaciones del sistema (Segmento representativo)
ESTACIONES = [
    "Portal Norte", "Calle 100", "Héroes", "Calle 72",
    "Marly", "Calle 26", "Avenida Jiménez", "Portal Eldorado", "Portal Sur"
]

# Rutas/Servicios y la secuencia ordenada de estaciones por las que transitan
RUTAS: Dict[str, List[str]] = {
    "Ruta 1 (Fácil)": ["Portal Norte", "Calle 100", "Héroes", "Calle 72", "Marly", "Calle 26", "Avenida Jiménez"],
    "Express B13/F13": ["Portal Norte", "Calle 100", "Calle 72", "Avenida Jiménez"],
    "Express K43/G43": ["Portal Eldorado", "Avenida Jiménez", "Portal Sur"],
    "Express K16/B16": ["Portal Eldorado", "Calle 26", "Marly", "Calle 100", "Portal Norte"],
    "Ruta 8 (Circular)": ["Portal Sur", "Avenida Jiménez", "Calle 26"]
}

# Tiempo medio en minutos entre estaciones consecutivas de una misma ruta
TIEMPO_ENTRE_ESTACIONES = 3
TIEMPO_TRASBORDO = 5  # Penalización por trasbordo en minutos


# ==========================================================
# 2. MOTOR DE INFERENCIA Y REGLAS LÓGICAS
# ==========================================================

class MotorInferenciaTransMilenio:

    @staticmethod
    def regla_conexion_directa(estacion_origen: str, estacion_destino: str) -> List[Dict]:
        """
        REGLA 1: ∀ r ∈ Rutas, (Origen ∈ r ∧ Destino ∈ r ∧ Pos(Origen) < Pos(Destino))
                 ⇒ ConexiónDirecta(Origen, Destino, r)
        """
        opciones_directas = []
        for nombre_ruta, estaciones in RUTAS.items():
            if estacion_origen in estaciones and estacion_destino in estaciones:
                idx_orig = estaciones.index(estacion_origen)
                idx_dest = estaciones.index(estacion_destino)

                if idx_orig < idx_dest:
                    paradas = idx_dest - idx_orig
                    tiempo = paradas * TIEMPO_ENTRE_ESTACIONES
                    opciones_directas.append({
                        "tipo": "Directa",
                        "trasbordos": 0,
                        "tiempo_estimado": tiempo,
                        "detalle": [f"Toma {nombre_ruta} desde '{estacion_origen}' hasta '{estacion_destino}' ({paradas} paradas)."]
                    })
        return opciones_directas

    @staticmethod
    def regla_conexion_trasbordo(estacion_origen: str, estacion_destino: str) -> List[Dict]:
        """
        REGLA 2: ∀ M ∈ Estaciones, (ConexiónDirecta(Origen, M, r1) ∧ ConexiónDirecta(M, Destino, r2))
                 ⇒ ConexiónTrasbordo(Origen, Destino, M, r1, r2)
        """
        opciones_trasbordo = []
        for estacion_intermedia in ESTACIONES:
            if estacion_intermedia in (estacion_origen, estacion_destino):
                continue

            # Buscar trayecto 1: Origen -> Intermedia
            trayectos_1 = MotorInferenciaTransMilenio.regla_conexion_directa(estacion_origen, estacion_intermedia)
            # Buscar trayecto 2: Intermedia -> Destino
            trayectos_2 = MotorInferenciaTransMilenio.regla_conexion_directa(estacion_intermedia, estacion_destino)

            for t1 in trayectos_1:
                for t2 in trayectos_2:
                    tiempo_total = t1["tiempo_estimado"] + t2["tiempo_estimado"] + TIEMPO_TRASBORDO
                    opciones_trasbordo.append({
                        "tipo": "Con Trasbordo",
                        "trasbordos": 1,
                        "tiempo_estimado": tiempo_total,
                        "estacion_trasbordo": estacion_intermedia,
                        "detalle": [
                            t1["detalle"][0],
                            f"Haz trasbordo en '{estacion_intermedia}' (tiempo estimado trasbordo: {TIEMPO_TRASBORDO} min).",
                            t2["detalle"][0]
                        ]
                    })
        return opciones_trasbordo

    @classmethod
    def buscar_mejor_ruta(cls, origen: str, destino: str) -> Optional[Dict]:
        """
        REGLA DE SELECCIÓN (Criterio Heurístico de Calidad de Ruta):
        MejorRuta = min_trasbordos(Rutas) -> min_tiempo(Rutas)
        """
        if origen not in ESTACIONES or destino not in ESTACIONES:
            return None

        if origen == destino:
            return {"tipo": "Misma Estación", "trasbordos": 0, "tiempo_estimado": 0, "detalle": ["Ya te encuentras en la estación destino."]}

        # Evaluar reglas lógicas
        rutas_directas = cls.regla_conexion_directa(origen, destino)

        if rutas_directas:
            # Si hay directas, la mejor es la de menor tiempo
            rutas_directas.sort(key=lambda x: x["tiempo_estimado"])
            return rutas_directas[0]

        # Si no hay directas, evaluar regla de trasbordo
        rutas_trasbordo = cls.regla_conexion_trasbordo(origen, destino)
        if rutas_trasbordo:
            rutas_trasbordo.sort(key=lambda x: x["tiempo_estimado"])
            return rutas_trasbordo[0]

        return None



# ==========================================================
# 3. INTERFAZ DE USUARIO Y PRUEBAS EN CONSOLA
# ==========================================================

def ejecutar_sistema():
    print("=" * 60)
    print(" SISTEMA BASADO EN CONOCIMIENTO: RUTAS TRANSMILENIO")
    print("=" * 60)
    print("Estaciones disponibles en el sistema:")
    for idx, est in enumerate(ESTACIONES, 1):
        print(f" {idx}. {est}")
    print("-" * 60)

    try:
        idx_origen = int(input("Seleccione el número de la estación de ORIGEN (Punto A): ")) - 1
        idx_destino = int(input("Seleccione el número de la estación de DESTINO (Punto B): ")) - 1
        if not (0 <= idx_origen < len(ESTACIONES) and 0 <= idx_destino < len(ESTACIONES)):
            print("\n[Error] Selección inváida. Elija un número de la lista.")
            return

        origen = ESTACIONES[idx_origen]
        destino = ESTACIONES[idx_destino]
        print(f"\n[Calculando mejor ruta desde '{origen}' hasta '{destino}'...]")
        resultado = MotorInferenciaTransMilenio.buscar_mejor_ruta(origen, destino)
        print("\n" + "=" * 60)
        print(" RESULTADO DE LA INFERENCIA LÓGICA")
        print("=" * 60)
        if resultado:
            print(f"Tipo de Ruta       : {resultado['tipo']}")
            print(f"Trasbordos         : {resultado['trasbordos']}")
            print(f"Tiempo Estimado    : {resultado['tiempo_estimado']} minutos")
            print("\nInstrucciones de Viaje:")
            for paso in resultado["detalle"]:
                print(f" -> {paso}")
        else:
            print("No se encontró una ruta lógica válida para conectar los dos puntos seleccionados.")
    except ValueError:
        print("\n[Error] Debe ingresar únicamente números enteros.")

if __name__ == "__main__":
    ejecutar_sistema()
